# Generated by Django 3.2.18 on 2023-03-06 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='runners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
