# Generated by Django 3.2.18 on 2023-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_run_runners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.TimeField(help_text='HH:MM'),
        ),
    ]
