# Generated by Django 3.2.18 on 2023-03-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(help_text='MM:DD:YYYY'),
        ),
    ]
