# Generated by Django 3.2.18 on 2023-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(help_text='DD/MM/YYYY'),
        ),
    ]
