# Generated by Django 3.2.18 on 2023-03-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_run_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
