# Generated by Django 3.2.18 on 2023-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_remove_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ICE',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
